/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serao_convivio;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Lara Trindade e João Miranda
 */
public class Interface_Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Interface_Principal
     */
    
    Serao_Convivio aux;
    int comb=0;
    
    /**
     *
     * @param c objeto do tipo Serao_Convivio
     */
    public Interface_Principal(Serao_Convivio c) {
        aux = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        increverConvivio = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Selec_Local = new javax.swing.JButton();
        Selec_Local1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Volta1 = new javax.swing.JButton();
        Pass_inscrever = new javax.swing.JPasswordField();
        Nmr_inscrever = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Res1 = new javax.swing.JTextField();
        Locais_insc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Menu1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nmr_inscrever1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        Volta2 = new javax.swing.JButton();
        Res2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        Pass_inscrever2 = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        increverConvivio.setText("Inscrever no Convívio");
        increverConvivio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increverConvivioActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        Selec_Local.setText("Entrar");
        Selec_Local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_LocalActionPerformed(evt);
            }
        });

        Selec_Local1.setText("Receitas");
        Selec_Local1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selec_Local1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1246, Short.MAX_VALUE)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(increverConvivio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Selec_Local, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Selec_Local1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(increverConvivio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Selec_Local, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Selec_Local1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        getContentPane().add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        Volta1.setText("Voltar");
        Volta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volta1ActionPerformed(evt);
            }
        });

        Pass_inscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_inscreverActionPerformed(evt);
            }
        });

        Nmr_inscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nmr_inscreverActionPerformed(evt);
            }
        });

        jLabel1.setText("Insira o seu número:");

        jLabel2.setText("Insira a sua palavra-pass:");

        jButton1.setText("Inscrever");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Res1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Res1ActionPerformed(evt);
            }
        });

        Locais_insc.setText("Continuar");
        Locais_insc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Locais_inscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Volta1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Locais_insc, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(Pass_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(323, 323, 323)
                                        .addComponent(Nmr_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Res1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nmr_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pass_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Res1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volta1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Locais_insc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, "card3");

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        Menu1.setText("Voltar para o menu principal");
        Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Insira o seu número de identificação");

        jLabel4.setText("Selecione o local que quer visitar");

        Nmr_inscrever1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nmr_inscrever1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Password");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Imprimir locais e lotação");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Volta2.setText("Voltar");
        Volta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volta2ActionPerformed(evt);
            }
        });

        Res2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Res2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton4.setText("Imprimir Guest List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        Pass_inscrever2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_inscrever2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Pass_inscrever2)
                                    .addComponent(Nmr_inscrever1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(125, 125, 125))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(Res2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Volta2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Menu1)
                        .addGap(94, 94, 94))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nmr_inscrever1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Pass_inscrever2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Res2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Volta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel3, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void increverConvivioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increverConvivioActionPerformed
        // TODO add your handling code here:
        if(comb == 0){
            int i;
            ArrayList<String> l = new ArrayList<>();
            System.out.println(aux.getLocais().size());
            for(i=0; i<aux.getLocais().size(); i++){
                l.add(aux.getLocais().get(i).getNome_local());
                jComboBox2.addItem(l.get(i));
                jComboBox1.addItem(l.get(i));  
            }
            comb = 1;
        }
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_increverConvivioActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        aux.terminar();
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("");
        Res2.setText("");
        jTextArea1.setText("");
        Pass_inscrever2.setText("");
        Nmr_inscrever1.setText("");
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_Menu1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            int nmr, i, a=0;
            char[] pass;
            char[] p = new char[] {'n', 'u', 'l', 'l'};
            nmr = Integer.parseInt(Nmr_inscrever.getText());
            pass = Pass_inscrever.getPassword();

            for(i=0; i<aux.getPessoas().size(); i++){
                if((aux.getPessoas().get(i).getNmr() == nmr)){//e o nmr existe nas Pessoas_Dei
                    a=1;
                    if ((Arrays.equals(aux.getPessoas().get(i).getPal_chave(), p)) ){//E a palavra pass esta a null
                        aux.escolher_pass(nmr, pass);
                        Res1.setText("Password definida com sucesso!");
                        Pass_inscrever.setText("");
                        Nmr_inscrever.setText("");
                        Pass_inscrever.setText("");
                        break;
                    }
                    else{
                        Res1.setText("A pessoa já tem uma password definida!");
                        Nmr_inscrever.setText("");
                        break;                        
                    }
                }      
            }
            if(a!=1){
                    Res1.setText("Número não existe!");
                    Nmr_inscrever.setText("");
                }
        } catch (NumberFormatException e) {
            Res1.setText("Numero com caracteres invalido!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Res1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Res1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Res1ActionPerformed

    private void Volta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volta1ActionPerformed
        // TODO add your handling code here:
        Res1.setText("");
        Nmr_inscrever.setText("");
        Pass_inscrever.setText("");
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_Volta1ActionPerformed

    private void Locais_inscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Locais_inscActionPerformed
        // TODO add your handling code here:
        Res1.setText("");
        Nmr_inscrever.setText("");
        Pass_inscrever.setText("");
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);

    }//GEN-LAST:event_Locais_inscActionPerformed

    private void Pass_inscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_inscreverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass_inscreverActionPerformed

    private void Nmr_inscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nmr_inscreverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nmr_inscreverActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:                  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Nmr_inscrever1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nmr_inscrever1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nmr_inscrever1ActionPerformed

    private void Selec_LocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_LocalActionPerformed
        // TODO add your handling code here:
        if(comb == 0){
            int i;
            ArrayList<String> l = new ArrayList<>();
            System.out.println(aux.getLocais().size());
            for(i=0; i<aux.getLocais().size(); i++){
                l.add(aux.getLocais().get(i).getNome_local());
                jComboBox2.addItem(l.get(i));
                jComboBox1.addItem(l.get(i));  
            }
            comb = 1;
        }
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_Selec_LocalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Local l;
        Pessoa_Dei pess;
        String a;
        boolean x;
        int i,nmr,j,xx=0;
        //char[] p = new char[] {'n', 'u', 'l', 'l'};
        char[] pass;
        pass = Pass_inscrever2.getPassword();
        nmr = Integer.parseInt(Nmr_inscrever1.getText());
        a = (String) jComboBox2.getSelectedItem();
        System.out.println(a);
        
        for(i=0; i<aux.getPessoas().size(); i++){
            if((aux.getPessoas().get(i).getNmr() == nmr) && (Arrays.equals(aux.getPessoas().get(i).getPal_chave(), pass)) ){//e o nmr existir nas Pessoas_Dei e a palavra pass é a correta
                pess = aux.getPessoas().get(i);
                //System.out.println("pessoa->"+pess.getNome());
                for(j=0; j< aux.getLocais().size(); j++){
                    //System.out.println(aux.getLocais().get(j).getNome_local().compareTo(a));
                    if(aux.getLocais().get(j).getNome_local().compareTo(a) == 0){//encontra o local com esse nome
                        l = aux.getLocais().get(j);//coloca o local do tipo Local em l
                        //System.out.println("local->"+l.getNome_local());
                        x = aux.escolher_locais_inscricoes(l, pess);
                        //System.out.println("boolean -> "+x);
                        xx=1;
                        if (x == true){
                            Res2.setText("Local inscrito com sucesso!");
                            //Pass_inscrever2.setText("");
                            //Nmr_inscrever1.setText("");
                        }
                        else if (x == false){
                            Res2.setText("Não pode selecionar o local!");
                        }
                    }
                }
            }
            else if(xx == 0){
                Res2.setText("Password  ou número inválida");
                //Pass_inscrever2.setText("");
                //Nmr_inscrever1.setText("");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        int [] nmr_ins = new int[aux.getLocais().size()];
        int n,i,z,k=0,max=0,y;
        //System.out.println("imprimir nmr locais->"+aux.getLocais().size());
        for(z=0; z<aux.getLocais().size(); z++){
            n = aux.llocais(aux.getLocais().get(z));
            nmr_ins[k] = n;//coloca o nmr de pessoas inscritas no local (por ordem no array de locais)
            k++;
            
            if (aux.getLocais().get(z).local_bar() == false)
                jTextArea1.append(aux.getLocais().get(z).getNome_local()+" -> Nmr inscritos: "+n+"\n");
            else if(aux.getLocais().get(z).local_bar() == true)
                jTextArea1.append(aux.getLocais().get(z).getNome_local()+" -> Nmr inscritos: "+n+"  Lotação maxima: " + aux.getLocais().get(z).lotacao()+"\n");
        }
        
        jTextArea1.append("\n -------- Locais ordenados por ordem decrecente --------\n");
        for(z=0; z<aux.getLocais().size(); z++)
        {
            for (i = 0; i < nmr_ins.length; i++)
            {
                if (nmr_ins[i] > max) 
                    max = nmr_ins[i];
            }
            //System.out.println(max);
            for (y = 0; y < nmr_ins.length; y++)
            {
                if (nmr_ins[y] == max)
                { 
                    jTextArea1.append(aux.getLocais().get(y).getNome_local() + "\n");
                    nmr_ins[y] = -1;
                }
            }
            max = 0;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Volta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volta2ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("");
        Res2.setText("");
        jTextArea1.setText("");
        Pass_inscrever2.setText("");
        Nmr_inscrever1.setText("");
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_Volta2ActionPerformed

    private void Res2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Res2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Res2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("");
        String a;
        ArrayList<String>gg = new ArrayList();
        int i, xx=0, k;
        a = (String) jComboBox1.getSelectedItem();
        ArrayList<Pessoa_Dei> guest = new ArrayList<>();
        double perc;
        int maxguest=0;
        Ficheiros f = new Ficheiros();
        
        perc = f.percentagem_gl(aux.getLocais());

        for(i=0; i<aux.getLocais().size() ; i++){
            if(aux.getLocais().get(i).getNome_local().compareTo(a) == 0){
                xx=i;//indice do local
                maxguest = (int)((aux.getLocais().get(i).lotacao()) * perc);
            }
        }
        //System.out.println(maxguest);
        //System.out.println("xx->"+xx);
        if(guest.size() < maxguest){
            //aux.guest_list(aux.getLocais().get(xx));
            gg = aux.guest_list(aux.getLocais().get(xx));
            for(k=0; k<aux.getPessoas().size(); k++)
            {
                if(guest.size() < maxguest)
                {
                    for(i=0; i<gg.size(); i++)
                    {   
                        //System.out.println("tam "+gg.size());
                        //System.out.println("\n->"+k);
                        //System.out.println("\n->"+aux.getPessoas().get(k).getNome());
                        //System.out.println("\n->"+gg.get(i));
                        if( aux.getPessoas().get(k).getNome().compareTo(gg.get(i)) == 0)
                            guest.add(aux.getPessoas().get(k));
                    }
                }
            }
            //System.out.println(aux.guest_list(aux.getLocais().get(xx)));
        }
        
        for(i=0; i<guest.size(); i++){
            if(guest.get(i).aluno() == false)//a pessoa NAO é estudante
                jTextArea2.append("Nome: "+guest.get(i).getNome()+" Perfil: "+guest.get(i).getPerfil()+"\n");
            else if(guest.get(i).aluno() == true){
                    jTextArea2.append("Nome: "+guest.get(i).getNome()+" Perfil: "+guest.get(i).getPerfil()+" Curso: "+guest.get(i).curso()+"\n");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void Pass_inscrever2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_inscrever2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass_inscrever2ActionPerformed

    private void Selec_Local1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selec_Local1ActionPerformed
        // TODO add your handling code here:
        double i;
        String out;
        i = aux.receitass();
        JOptionPane.showMessageDialog(Menu1, i, "Receita", WIDTH);
        /*jPanel2.setVisible(false);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);*/
    }//GEN-LAST:event_Selec_Local1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Locais_insc;
    private javax.swing.JButton Menu1;
    private javax.swing.JTextField Nmr_inscrever;
    private javax.swing.JTextField Nmr_inscrever1;
    private javax.swing.JPasswordField Pass_inscrever;
    private javax.swing.JPasswordField Pass_inscrever2;
    private javax.swing.JTextField Res1;
    private javax.swing.JTextField Res2;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Selec_Local;
    private javax.swing.JButton Selec_Local1;
    private javax.swing.JButton Volta1;
    private javax.swing.JButton Volta2;
    private javax.swing.JButton increverConvivio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
